cloudflare_account_id: ENC[AES256_GCM,data:Urf8bi6W7HJYsdENRFV+4luGo7chtQwwWOYNdOunsN0=,iv:z7d49Cd8GqBokzDPPuPwseRJ/XpTuZiJ+dwH0R9/5yk=,tag:QZNkhA3IUwsYAGH1j3LwWw==,type:str]
cloudflare_dns_edit_token_old: ENC[AES256_GCM,data:tMTWWWplxbluzNhu98hg/v3qCC+fs0v7/uoCvi+7Dh6jZGXFICY5yQ==,iv:+7zP6e4Ur6Wti19CvZRHy7vWbLw/eb8S4yL+a8SyQlY=,tag:vtJWV8hXShQ6QjW75lDiuA==,type:str]
cloudflare_dns_edit_token: ENC[AES256_GCM,data:hdcYHwgiSe/tu9u8IaF8wYmveURSlQJY5AlD4nL/xPLsRJicBC8AiQ==,iv:Nfyn7BqGlW/wWPsDU+0XbQ0xrI3axLMPhrJAEBTd5cM=,tag:OS2vgJtrViYFSxsM2LtXyQ==,type:str]
cloudflare_dns_edit_token_name: ENC[AES256_GCM,data:je6WdCHYI1P64xEMF6XWtgfj,iv:HtAPiAHA3/f668iegvWxthUEJ5w+M1Qfkx+7d96CnaU=,tag:rMi3+ODw+qML1sEVRYBXEg==,type:str]
cloudflare_zone_id: ENC[AES256_GCM,data:QVELcjGdaNAazM5KSeGKwfLSU1hLS1JTj4TVSK4MR0E=,iv:DosvC4WW3BcWD5x01Ax8GNLS7+TUeR8jlaXMqtibaus=,tag:aoi3m+GwZnh01Ckrke4MdQ==,type:str]
cloudflare_zone_name: ENC[AES256_GCM,data:wzEo3CzPQ8U2+LE=,iv:B543TQSDqCUfNQ4mZUllg51fS6zzEPaB73kx25/OG08=,tag:lhqFeNkuh4Yf4M+/wRZ1Rg==,type:str]
cloudflare_zone_name_ol: ENC[AES256_GCM,data:evS+8BGr652icClDzjktWa8=,iv:t4kzj8ZZ+9SC1K7331DFHPeGNR2A0b4FSaj7D1YW7qc=,tag:SRR5bOGhYiS+mZNNlAtklg==,type:str]
letsencrypt_email: ENC[AES256_GCM,data:gbAPPiPgsnt/D4IK0aMnUS6lHZix32I=,iv:TjJLzGy18pkM4z6KwnTB2S8ucpybObrm0nhRfIIpygU=,tag:rtIg+2gYpFpLwtX8K1TS6g==,type:str]
cloudflare_zone_read_token: ENC[AES256_GCM,data:/gEPEGndUUzUOXyYp7S6dE1/qrU3ptirncUAXloI7mtKyXVYxVw8MQ==,iv:xygLIvMBPQsmVYlhIwV3OgS/yKIjGbtpogjtR7T5Jjc=,tag:oHfHlDDMrAGEG/DHA80uAw==,type:str]
letsencrypt_domain_external: ENC[AES256_GCM,data:V1Kb6XYPTPGaYFc=,iv:xxC+TDXV7WM/7fhXHGvWUJN3JANp0GvEsPUyXVKT6Ls=,tag:U82g9DpAdyNfek6EJIeMCg==,type:str]
letsencrypt_domain_external_sans:
    - ENC[AES256_GCM,data:YFjVNNzad/l8gLNrcQ==,iv:ASMEOG3a+o1MWNl25QUtVIAMKCY/qxvdBVFgC3BaG8c=,tag:nK0zrn9F+anT95meoWogxg==,type:str]
letsencrypt_domain_internal: ENC[AES256_GCM,data:kZuD9ozJibw3nboDPYMZ,iv:RroK2Dkeb8YCetp0JccLbLVdqLxjx/to2hmOYiXmh/4=,tag:J7tx2aeQuGvjsVyLQWRXSw==,type:str]
letsencrypt_domain_internal_sans:
    - ENC[AES256_GCM,data:vNzTUKJgYFeOPMlUpE/+ME8=,iv:PwKqdl4PnbMIhp/Shxn+D+YI668CgdnzWLnXy2rU4wI=,tag:gteAWLX+3UUG4fjlrV+1Ig==,type:str]
    - ENC[AES256_GCM,data:mJKr4h7ftRZIerhiAofU6bWd,iv:ngUM43mcbq8Vk+fR7GkeTxGCDmZgbDs/uryo4UGfQ6I=,tag:LHYBxw6BdYBgXDDwhLOPTQ==,type:str]
    - ENC[AES256_GCM,data:nhA0sgeuGTAzdFTaKoE7NHXH,iv:MCBn6LauBIXwYenUYtvi3cNFeid2X56PTyND5U4z5Ps=,tag:g3RX6EaRD0wguDrIpUjVLA==,type:str]
letsencrypt_domain_ol: ENC[AES256_GCM,data:1PWhUtoeB0npraX8i4YY1cU=,iv:HBMxrd/YDdajTAjDyBagT/k54b5xL2ptixeB3lA7Oy4=,tag:ok4Kpru8wUwLWbqqxlHWvQ==,type:str]
letsencrypt_domain_ol_sans:
    - ENC[AES256_GCM,data:xi4NbszYImdh1L/eAqKhCMJFFw==,iv:48F1d+fS0HW82OqwuT9qbksWFYEhT2YKmEJ0z1G5Yng=,tag:8Xx3GMqthxvxWVl/ZziTMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15j42dspmmwprjau6l48xp05d97s8ml5s3tjxrfwvm37tvuynssuqtsevkj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UUNIQkY5YkZCY1Juamx2
            eVlOb1BuSTNwWWcxZkZTenZOMGFGSFE4ckg0CklEOGNHRjdENG5SV2VCdlNTcXlw
            Qnh0YnROVUkrc29FeW5NL3oyVzU2L0UKLS0tIFlmcEFFaDFVNWR1YjNVTmpWTDZ1
            b3pZMDRTOERESjM2RzZUZUhTblFnUUkK/doVNXZg3Rl5ZtI69DHlDc04cSh9BXRV
            /ESNzA6kdf0c7PQT/DZJIovcGEOamAqhHLyNDzvcoBCJgnKIXvlwfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-28T12:53:09Z"
    mac: ENC[AES256_GCM,data:pjbXZaM6sT1ArzAn3BJvtLGk4Oni+7cpad8bEa9Zuo8ssw/QcLQ/IE6ZZpBGQ1aa9+zARq1CgIgtapFjPWhz4LcaCyXjjabF2HABFs/KnsYQ79OnRM3mZLNttoarLaBiX1WRSuq2Bc2XtF2q52AecdS00CopMOzA0XgvrqEFjPM=,iv:foMVFpgwFXGYYA2kYQDGWIrI6d55O3/yzqPb8UjJYPw=,tag:1WcyXp2cDOogn0UqqUdnEg==,type:str]
    pgp:
        - created_at: "2021-08-18T08:08:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMAz/c2vn977oWARAAcNvB+CAzcB4vusPNZYK1P9cKpXvw/gOKq3ZwaDxq3pIf
            2pvKJOXfD0WGoKsruhQMhAQYvpItHQEQFwgF03Mkq0jP0GbFo9h7cWuUBAUtKho9
            0GJj1hf0pFzlraVkhZEuKfj1cxKJOT5KWZI/hD+32DXfXSaUtRLlEdVOwLx6xQpY
            GDLDHw5l9+fYWs8S/WwVTKlkm7wRlGCNyEbhlhPpyztljIp1PTmvipyPBOzgBcgI
            0VfZx91qYiXvJyjZ+ByMmpM+gssRY1FLiu69V4J9UeIaQ7kciX/eQJtXqi2yOOzp
            33/bfgbBDhgvTtzv0GKTviknheuA1/bfbxJ5chavUu0IV9PRj3raWMWywCyOWaTJ
            pMcz/g7w6SgNUOdFti0GT1k4Su+hjnRoPc4VzuTBVGpVVriwrGrdb9uh/f0nXCB1
            qIgq2BQKL03237Ii1PzI7Vlv+CMHSjapVs3YNhH4RE4fUmvCexGmQmnIFOg8jI9+
            Myh+nEByXaogtGcrG3zKVlXb5v0Q8iQcZajfo5pUfGG75C81Pzsx2KqKTGscKyp4
            AcpwQt2yac/z0Bi8CFrwAOdTg7XEaQvYrreq2T7Z7wKiW4dxtKTVMNLq7tQI0DDi
            9jA5yCRWkFAkR3+wb/XWXDwuz8c7FvO0klAyT0ZOKPtEtofnBFhUPcYIzkr7UbTS
            5gEFrIl7xmW3XU/e4R7BlpuQL8x7ZqyPpjH6XDfEGCLv3K3os684sbDEAGgAEV97
            eAXl+3PYGEItxhPhghKBOhDkm4++u1zLhltEU8fePrr+O+ImdO9tAA==
            =Wnrg
            -----END PGP MESSAGE-----
          fp: 978C4D08058BA26EB97CB51820782DBCACFAACDA
    unencrypted_suffix: _unencrypted
    version: 3.7.3
