---
traefik_redis_bind_port: 6379
traefik_redis_bind_ip: container0.{{ subdomain_mgmt }}
service_exposed_preset: internal-https
service_domain_preset: socozy
service_local_data_dir: /srv/services
service_role_owner: root
service_role_group: root

cloudflare_public_ip: "{{ personal_public_ip }}"

service_exposed_presets:
  internal-https:
    service_entrypoints_secure:
      - web-internal-secure
    container_expose_public: false
  external-https:
    service_entrypoints_secure:
      - web-external-secure
      - web-internal-secure
    container_expose_public: true

service_domain_presets:
  socozy:
    service_cert_resolver: socozy
    service_cert_domains:
      - main: "{{ letsencrypt_domain_external }}"
        sans: "{{ letsencrypt_domain_external_sans }}"
  ol:
    service_cert_resolver: ol
    service_cert_domains:
      - main: "{{ letsencrypt_domain_ol }}"
        sans: "{{ letsencrypt_domain_ol_sans }}"

service_entrypoints_secure: "{{ service_exposed_presets[service_exposed_preset].service_entrypoints_secure }}"
container_expose_public: "{{ service_exposed_presets[service_exposed_preset].container_expose_public }}"

service_cert_resolver: "{{ service_domain_presets[service_domain_preset].service_cert_resolver }}"
service_cert_domains: "{{ service_domain_presets[service_domain_preset].service_cert_domains }}"
container_podman_network: services

firewalld_enabled: false
