---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: send
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: send-redis
      namespace: default
  values:
    image:
      repository: registry.gitlab.com/timvisee/send
      tag: latest
    env:
      TZ: ${TZ}
      BASE_URL: "send.${SECRET_DOMAIN}"
      REDIS_HOST: send-redis.default.svc.cluster.local
      REDIS_PORT: 6379
      FILE_DIR: /uploads
      MAX_FILE_SIZE: 5368709120
      MAX_EXPIRE_SECONDS: 2630000
      DEFAULT_DOWNLOADS: 50
      EXPIRE_TIMES_SECONDS: 3600,86400,604800,2592000,31536000
    envFrom:
      - secretRef:
          name: send-secret
    service:
      main:
        ports:
          http:
            port: 1443
    persistence:
      data:
        enabled: true
        existingClaim: send-appdata
        subPath:
          - path: uploads
            mountPath: /uploads
    podSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
      fsGroupChangePolicy: "OnRootMismatch"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx-internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:email-fast-outline
          hajimari.io/group: tools
          nginx.ingress.kubernetes.io/proxy-body-size: 5G
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &host "send.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
