---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./cilium/ks.yaml
  #- ./descheduler/ks.yaml
  #- ./external-secrets/ks.yaml
  #- ./intel-device-plugin/ks.yaml
  #- ./kube-cleanup-operator/ks.yaml
  - ./kubernetes-replicator/ks.yaml
  - ./metrics-server/ks.yaml
  #- ./node-feature-discovery/ks.yaml
  - ./reloader/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./external-secrets/ks.yaml
