---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubernetes-replicator-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://helm.mittwald.de
  timeout: 3m
