---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: flux-system
  name: repositories
resources:
  - bitnami-charts.yaml
  - bjw-s.yaml
  - coredns-charts.yaml
  - external-dns.yaml
  - kustomization.yaml
  - metrics-server-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - weave-gitops.yaml
  - cilium-charts.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - hajimari.yaml
  - stakater.yaml
  - kubernetes-replicator-charts.yaml
  - nextcloud.yaml
  - ext-postgres-operator.yaml
  - zalando-postgres-operator.yaml
