---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-workloads-matrix-synapse-db
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-workloads-crunchy-postgres-operator
  path: ./k8s/k8s-prod/workloads/comms/matrix-synapse/db
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-workloads-matrix-synapse-app
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-workloads-matrix-synapse-db
    - name: cluster-workloads-external-secrets-stores
    - name: cluster-workloads-cert-manager-issuers
    - name: cluster-workloads-rook-ceph-cluster
    - name: cluster-workloads-volsync
  path: ./k8s/k8s-prod/workloads/comms/matrix-synapse/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: matrix-synapse
      namespace: comms
