---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tts-mimic3
  namespace: voiceassistant
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 0
  upgrade:
    remediation:
      retries: 0
  values:
    image:
      repository: ghcr.io/ramblurr/mimic3
      tag: main@sha256:e9343318a1575b7fe147efcfa0c4575bbd44f97a1c81de015705467aac374315
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    env:
      MIMIC3_CONFIG_PATH: /mimic3/config
      MIMIC3_DISABLE_CHOWN: "true"
      MIMIC3_SPONSOR: "true"
    volumeClaimTemplates:
      - name: mimic3-data
        mountPath: /home/mimic3/.local/share/mycroft/mimic3
        storageClass: "${DEFAULT_STORAGE_CLASS}"
        accessMode: "ReadWriteOnce"
        size: 1Gi
    service:
      main:
        ports:
          http:
            port: 59125
    ingress:
      main:
        enabled: true
        ingressClassName: nginx-internal-voiceassistant
        annotations:
          hajimari.io/enable: "false"
          nginx.ingress.kubernetes.io/proxy-body-size: 100M
          nginx.ingress.kubernetes.io/proxy-buffering: "off"
        hosts:
          - host: &host mimic3.${SECRET_DOMAIN_INTERNAL}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      reloader.stakater.com/auto: "true"
