---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/master/v1.27.4-standalone-strict/statefulset-apps-v1.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &name kitchen-base-skills
  namespace: voiceassistant
spec:
  serviceName: *name
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      containers:
        - name: skill-wikipedia
          image: docker.io/smartgic/ovos-skill-wikipedia:0.0.8aa
          env: &base-env
            - name: TZ
              value: Europe/Berlin
            - name: HOME
              value: /home/ovos
          volumeMounts: &skill-mnt
            - name: ovos-mycroft-config
              mountPath: /home/ovos/.config
              subPath: kitchen-skills/config
            - name: ovos-mycroft-config
              mountPath: /home/ovos/.local/share
              subPath: kitchen-skills/share
            - name: ovos-tmp
              mountPath: /tmp/mycroft
        - name: skill-weather
          image: docker.io/smartgic/ovos-skill-weather:0.0.8a
          volumeMounts: *skill-mnt
          env: *base-env
        - name: skill-volume
          image: docker.io/smartgic/ovos-skill-volume:0.0.8aa
          volumeMounts: *skill-mnt
          env: *base-env
        - name: skill-date-time
          image: docker.io/smartgic/ovos-skill-date-time:0.0.8aa
          volumeMounts: *skill-mnt
          env: *base-env
        - name: skill-stop
          image: docker.io/smartgic/ovos-skill-stop:0.0.8aa
          volumeMounts: *skill-mnt
          env: *base-env
        - name: skill-personal
          image: docker.io/smartgic/ovos-skill-personal:0.0.8aa
          volumeMounts: *skill-mnt
          env: *base-env
        - name: skill-fallback-unknown
          image: docker.io/smartgic/ovos-skill-fallback-unknown:0.0.8aa
          volumeMounts: *skill-mnt
          env: *base-env
        - name: skill-hello-world
          image: docker.io/smartgic/ovos-skill-hello-world:0.0.8aa
          volumeMounts: *skill-mnt
          env: *base-env
        - name: skill-alerts
          image: docker.io/smartgic/ovos-skill-alerts:0.0.8aa
          volumeMounts: *skill-mnt
          env: *base-env
        # - name: skill-wolfie
        #   image: docker.io/smartgic/ovos-skill-wolfie:alpha@sha256:4daa10e6e2fa0d269826e656f00316677d39ec27393c6bf149230fbda65b421e
        #   volumeMounts: *skill-mnt
        #   env: *base-env
        - name: skill-jokes
          image: docker.io/smartgic/ovos-skill-jokes:alpha@sha256:c904abe4d8bc3f6bd54fceb3c6a83d2c82961828ecadada637cadc031ad366e5
          volumeMounts: *skill-mnt
          env: *base-env
        - name: skill-homeassistant
          image: ghcr.io/ramblurr/skill-homeassistant-dev:rolling@sha256:37f5900e4d75315a0d933e7d894db52f9db7d8afae552753b17acdf01186f851
          volumeMounts: *skill-mnt
          env: *base-env
        - name: skill-chatgpt
          image: ghcr.io/ramblurr/skill-ovos-fallback-chatgpt-dev:rolling@sha256:5e643b8609988852b8ea24a188066985bd231255783a3c74c813242dd08fa1dd
          volumeMounts: *skill-mnt
          env: *base-env

      volumes:
        - name: ovos-mycroft-config
          persistentVolumeClaim:
            claimName: ovos-data-nfs
        - name: ovos-tmp
          emptyDir: {}
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsUser: 1000
