---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invoiceninja
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: invoiceninja-secret
    creationPolicy: Owner
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: clients.${SECRET_DOMAIN_WORK}
        property: APP_KEY
    - secretKey: IN_PASSWORD
      remoteRef:
        key: clients.${SECRET_DOMAIN_WORK}
        property: IN_PASSWORD
    - secretKey: mariadb-root-password
      remoteRef:
        key: clients.${SECRET_DOMAIN_WORK}
        property: mariadb-root-password
    - secretKey: mariadb-replication-password
      remoteRef:
        key: clients.${SECRET_DOMAIN_WORK}
        property: mariadb-replication-password
    - secretKey: mariadb-password
      remoteRef:
        key: clients.${SECRET_DOMAIN_WORK}
        property: mariadb-password
