---
collections:
  - name: ansible.netcommon
    version: 5.0.0
  - name: containers.podman
    version: 1.10.1
  - name: community.general
    version: 6.5.0
  - name: ansible.posix
    version: 1.5.1
  - type: git
    name: https://github.com/Ramblurr/ramblurr.freenas.git
    version: main
  - name: community.sops
    version: 1.6.1
  - name: community.healthchecksio
    version: 1.3.0
  - name: git+https://github.com/prometheus-community/ansible.git
    version: main
  - name: vyos.vyos
    version: 4.0.1
roles:
  - name: m3nu.ansible_role_borgbackup
    version: v0.9.4
  - name: rmblr.traefik_redis_service
    src: git+https://github.com/Ramblurr/ansible-role-traefik-redis-service.git
    version: main
...
