---
collections:
  - name: ansible.netcommon
    version: 5.2.0
  - name: containers.podman
    version: 1.10.4
  - name: community.general
    version: 7.4.0
  - name: ansible.posix
    version: 1.5.4
  - type: git
    name: https://github.com/Ramblurr/ramblurr.freenas.git
    version: main
  - name: community.sops
    version: 1.6.6
  - name: community.healthchecksio
    version: 1.3.1
  - name: prometheus.prometheus
    version: 0.6.0
  - name: vyos.vyos
    version: 4.1.0
roles:
  - name: m3nu.ansible_role_borgbackup
    version: v0.9.4
  - name: rmblr.traefik_redis_service
    src: git+https://github.com/Ramblurr/ansible-role-traefik-redis-service.git
    version: main
