---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-workloads-readarr-audiobooks
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-workloads-rook-ceph-cluster
    - name: cluster-workloads-external-secrets-stores
    - name: cluster-workloads-volsync
  path: ./k8s/k8s-prod/workloads/downloads/readarr-audiobooks/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: readarr-audiobooks
      namespace: downloads
  interval: 30m
  retryInterval: 1m
  timeout: 3m
