---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-system
  - rook-ceph
  - networking
  - monitoring
  - cert-manager
  - flux-system
  - database
  - default
  - qemu-guest-agent
